import AddBlog from "@/components/blog/addBlog";
import Footer from "@/components/landingPage/footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "MyFitPal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <main className="m-10 mx-72">
        <AddBlog />
        <section>{children}</section>
      </main>
      <Footer />
    </>
  );
}
